In [ ]:
# obtain gguf
# read set values from yaml
!set model_url
!set GIT_LFS_SKIP_SMUDGE=1 && git clone $model_url
!set model_name=regex model_url_rfind_slash
!python llama.cpp/convert_hf_to_gguf.py $model_name --outfile ./$model_name+'.gguf'
!llama-quantize $model_name.gguf $model_name+$quantization_type.gguf $quantization_type N=?-1?

In [ ]:
import benchmark
import time
for model_name in ["olmo2_IQ4_XS"]:#,"smolm2-pruned-sparsegpt-q4km"]:
    model_path=f'/mnt/d/Inno/Thesis/out/olmo2/olmo2_IQ4_XS.gguf'
    benchllm=benchmark.BenchLLM('../../llama.cpp/build/bin/llama-server','../../llama.cpp/build/bin/llama-perplexity',model_path)
    time.sleep(10) # wait for previous model free and server to close
    benchllm.start_server()
    time.sleep(150) # wait for model to load
    benchllm.bench() # stop server itself
    benchllm.save_to_file(f'./{model_name}')

In [ ]:
model_path=f'/mnt/d/Inno/Thesis/{model_name}.gguf'
benchllm=benchmark.BenchLLM('../../llama.cpp/bin/llama-server','../../llama.cpp/bin/llama-perplexity',model_path)
time.sleep(10) # wait for previous model free and server to close
benchllm.start_server()

In [2]:
import benchmark
benchllm=benchmark.BenchLLM('##','##','##')
result_df=benchllm.compare_results('../../out/benchmark_results/smollm2','smollm2_q16.json')
# p value is calculated for accuracy with McNemar's test p-value relative to base model
result_df

/mnt/d/Inno/Thesis/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

json_files: ['smollm2-gptq-4.json', 'smollm2-sparsegpt-02-gptq-4.json', 'smollm2-sparsegpt-05-gptq-4.json', 'smollm2-wanda-02-gptq-4.json', 'smollm2-wanda-05-gptq-4.json', 'smollm2_IQ4_XS.json', 'smollm2_q16.json', 'smollm2_Q8_0.json', 'smollm2_unstructured_sparsegpt_0.2_IQ4_XS.json', 'smollm2_unstructured_sparsegpt_0.2_q16.json', 'smollm2_unstructured_sparsegpt_0.2_Q8_0.json', 'smollm2_unstructured_sparsegpt_0.5_IQ4_XS.json', 'smollm2_unstructured_sparsegpt_0.5_q16.json', 'smollm2_unstructured_sparsegpt_0.5_Q8_0.json', 'smollm2_unstructured_wanda_0.2_IQ4_XS.json', 'smollm2_unstructured_wanda_0.2_q16.json', 'smollm2_unstructured_wanda_0.2_Q8_0.json', 'smollm2_unstructured_wanda_0.5_IQ4_XS.json', 'smollm2_unstructured_wanda_0.5_q16.json', 'smollm2_unstructured_wanda_0.5_Q8_0.json']
200 2066
200 2066
207 2066
623 2066
200 2066
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
200 200
correct->incorrect 24
incorrect->correct 4
correct->incorrect 9
incorrect->correct 38
correct->incorrect 9
incorrect->correct 30
correct->incorrect 21
incorrect->correct 2
correct->incorrect 10
incorrect->correct 31
correct->incorrect 13
incorrect->correct 21
correct->incorrect 13
incorrect->correct 11
correct->incorrect 15
incorrect->correct 12
correct->incorrect 15
incorrect->correct 12
correct->incorrect 13
incorrect->correct 13
correct->incorrect 10
incorrect->correct 23
correct->incorrect 9
incorrect->correct 24
correct->incorrect 10
incorrect->correct 29
correct->incorrect 12
incorrect->correct 15
correct->incorrect 9
incorrect->correct 22
correct->incorrect 13
incorrect->correct 13
correct->incorrect 18
incorrect->correct 19
correct->incorrect 12
incorrect->correct 13
correct->incorrect 9
incorrect->correct 17

/mnt/d/Inno/Thesis/llm_on_edge/benchmark/benchmark.py:182: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_acc = dfs[base_model_idx][~fail_mask]['accuracy']
/mnt/d/Inno/Thesis/llm_on_edge/benchmark/benchmark.py:182: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_acc = dfs[base_model_idx][~fail_mask]['accuracy']
/mnt/d/Inno/Thesis/llm_on_edge/benchmark/benchmark.py:182: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_acc = dfs[base_model_idx][~fail_mask]['accuracy']
/mnt/d/Inno/Thesis/llm_on_edge/benchmark/benchmark.py:182: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_acc = dfs[base_model_idx][~fail_mask]['accuracy']
/mnt/d/Inno/Thesis/llm_on_edge/benchmark/benchmark.py:182: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  base_acc = dfs[base_model_idx][~fail_mask]['accuracy']

,method,accuracy,ppl,prefill,decode,flips,fail,p_value
0,smollm2-gptq-4.json,0.03,28696.56+-118347.11,nan+-nan,nan+-nan,0.12,0.00,"0.00,n=200"
1,smollm2-sparsegpt-02-gptq-4.json,0.28,65.78+-231.59,nan+-nan,nan+-nan,0.04,0.00,"0.00,n=200"
2,smollm2-sparsegpt-05-gptq-4.json,0.23,123.77+-690.73,nan+-nan,nan+-nan,0.04,0.00,"0.00,n=207"
3,smollm2-wanda-02-gptq-4.json,0.03,8329.09+-10295.34,nan+-nan,nan+-nan,0.03,0.00,"0.00,n=623"
4,smollm2-wanda-05-gptq-4.json,0.23,94.74+-312.68,nan+-nan,nan+-nan,0.05,0.00,"0.00,n=200"
5,smollm2_IQ4_XS.json,0.17,10.54+-0.55,44.21+-6.45,29.21+-6.16,0.07,0.01,"0.17,n=200"
6,smollm2_q16.json,0.13,9.68+-0.50,82.44+-13.62,11.18+-1.90,0.00,0.02,"nan,n=200"
7,smollm2_Q8_0.json,0.12,9.70+-0.50,56.00+-10.20,19.93+-4.10,0.07,0.01,"0.68,n=200"
8,smollm2_unstructured_sparsegpt_0.2_IQ4_XS.json,0.12,10.72+-0.57,43.52+-6.61,29.10+-7.21,0.07,0.01,"0.56,n=200"
9,smollm2_unstructured_sparsegpt_0.2_q16.json,0.11,9.94+-0.52,78.16+-11.85,10.41+-2.27,0.08,0.03,"0.56,n=200"
10,smollm2_unstructured_sparsegpt_0.2_Q8_0.json,0.13,9.95+-0.52,50.62+-10.67,19.20+-4.33,0.07,0.04,"1.00,n=200"
11,smollm2_unstructured_sparsegpt_0.5_IQ4_XS.json,0.20,16.35+-0.99,46.39+-6.31,29.54+-7.58,0.05,0.01,"0.02,n=200"
12,smollm2_unstructured_sparsegpt_0.5_q16.json,0.20,14.69+-0.85,81.39+-10.69,10.22+-2.08,0.04,0.01,"0.01,n=200"
13,smollm2_unstructured_sparsegpt_0.5_Q8_0.json,0.23,14.76+-0.85,53.29+-10.01,18.39+-4.09,0.05,0.01,"0.00,n=200"
14,smollm2_unstructured_wanda_0.2_IQ4_XS.json,0.14,10.64+-0.57,34.24+-4.08,20.29+-5.79,0.07,0.10,"0.56,n=200"
15,smollm2_unstructured_wanda_0.2_q16.json,0.20,9.85+-0.52,77.37+-12.90,10.38+-2.28,0.04,0.06,"0.02,n=200"
16,smollm2_unstructured_wanda_0.2_Q8_0.json,0.12,9.87+-0.52,54.97+-10.81,18.50+-4.14,0.07,0.05,"1.00,n=200"
17,smollm2_unstructured_wanda_0.5_IQ4_XS.json,0.14,16.95+-1.02,43.51+-5.85,28.49+-6.62,0.09,0.01,"0.87,n=200"
18,smollm2_unstructured_wanda_0.5_q16.json,0.13,14.97+-0.88,75.58+-12.79,10.58+-2.31,0.07,0.01,"0.84,n=200"
19,smollm2_unstructured_wanda_0.5_Q8_0.json,0.16,15.04+-0.87,53.27+-9.71,18.36+-4.30,0.06,0.02,"0.12,n=200"

In [ ]:
benchllm.calc_corr(result_df)

In [6]:
import benchmark
benchllm=benchmark.BenchLLM('##','##','##')
result_df=benchllm.compare_results('../../out/benchmark_results/olmo2','olmo2_q16.json')
result_df

json_files: ['olmo2_IQ4_XS.json', 'olmo2_q16.json', 'olmo2_Q8_0.json', 'olmo2_unstructured_sparsegpt_0.2_IQ4_XS.json', 'olmo2_unstructured_sparsegpt_0.2_q16.json', 'olmo2_unstructured_sparsegpt_0.2_Q8_0.json', 'olmo2_unstructured_sparsegpt_0.5_IQ4_XS.json', 'olmo2_unstructured_sparsegpt_0.5_q16.json', 'olmo2_unstructured_sparsegpt_0.5_Q8_0.json', 'olmo2_unstructured_wanda_0.2_IQ4_XS.json', 'olmo2_unstructured_wanda_0.2_q16.json', 'olmo2_unstructured_wanda_0.2_Q8_0.json', 'olmo2_unstructured_wanda_0.5_IQ4_XS.json', 'olmo2_unstructured_wanda_0.5_q16.json', 'olmo2_unstructured_wanda_0.5_Q8_0.json']

,method,accuracy,ppl,prefill,decode,flips,fail,p_value
0,olmo2_IQ4_XS.json,0.27,14.63+-0.88,63.05+-8.93,46.02+-11.05,0.07,0.01,"0.13,n=199"
1,olmo2_q16.json,0.23,13.81+-0.86,116.70+-16.48,17.34+-3.28,0.00,0.00,"nan,n=200"
2,olmo2_Q8_0.json,0.23,13.82+-0.86,71.51+-16.26,30.41+-6.32,0.07,0.01,"0.85,n=199"
3,olmo2_unstructured_sparsegpt_0.2_IQ4_XS.json,0.20,22.79+-1.61,70.80+-6.48,49.09+-11.09,0.09,0.04,"0.47,n=191"
4,olmo2_unstructured_sparsegpt_0.2_q16.json,0.23,21.16+-1.48,111.61+-17.77,15.82+-3.51,0.10,0.00,"1.00,n=200"
5,olmo2_unstructured_sparsegpt_0.2_Q8_0.json,0.23,21.18+-1.48,68.35+-13.53,29.15+-5.54,0.10,0.00,"1.00,n=200"
6,olmo2_unstructured_sparsegpt_0.5_IQ4_XS.json,0.22,17.31+-0.95,60.98+-6.27,45.44+-10.65,0.12,0.04,"0.88,n=191"
7,olmo2_unstructured_sparsegpt_0.5_q16.json,0.24,16.69+-0.97,126.12+-17.81,17.88+-4.28,0.10,0.03,"0.64,n=194"
8,olmo2_unstructured_sparsegpt_0.5_Q8_0.json,0.20,16.69+-0.96,60.81+-10.30,23.36+-8.17,0.11,0.01,"0.42,n=197"
9,olmo2_unstructured_wanda_0.2_IQ4_XS.json,0.26,14.68+-0.87,53.27+-7.28,34.54+-12.18,0.06,0.00,"0.21,n=200"
10,olmo2_unstructured_wanda_0.2_q16.json,0.22,13.95+-0.85,126.00+-16.59,19.10+-3.74,0.08,0.01,"1.00,n=199"
11,olmo2_unstructured_wanda_0.2_Q8_0.json,0.16,13.97+-0.85,61.86+-9.50,31.28+-7.91,0.11,0.01,"0.03,n=198"
12,olmo2_unstructured_wanda_0.5_IQ4_XS.json,0.18,18.70+-1.09,61.04+-8.64,42.99+-10.42,0.12,0.03,"0.06,n=194"
13,olmo2_unstructured_wanda_0.5_q16.json,0.19,17.63+-1.01,126.55+-20.03,17.75+-4.11,0.12,0.04,"0.27,n=193"
14,olmo2_unstructured_wanda_0.5_Q8_0.json,0.24,17.66+-1.01,75.87+-13.34,29.10+-6.68,0.10,0.01,"0.76,n=198"

In [7]:
benchllm.calc_corr(result_df)

,accuracy,ppl,prefill,decode,fail
accuracy,1.00000000000000000000,-0.16330923481015682808,0.03603748475667356566,-0.00596154400760356019,-0.40609140151650124917
ppl,-0.16330923481015682808,1.00000000000000000000,-0.05313132587145032865,0.19299858317697721199,0.31755720063898279504
prefill,0.03603748475667356566,-0.05313132587145032865,1.00000000000000000000,-0.76872987865107467176,0.07577854327597413620
decode,-0.00596154400760356019,0.19299858317697721199,-0.76872987865107467176,1.00000000000000000000,0.36737054663493851070
fail,-0.40609140151650124917,0.31755720063898279504,0.07577854327597413620,0.36737054663493851070,1.00000000000000000000