In [ ]:
# obtain gguf
# read set values from yaml
!set model_url
!set GIT_LFS_SKIP_SMUDGE=1 && git clone $model_url
!set model_name=regex model_url_rfind_slash
!python llama.cpp/convert_hf_to_gguf.py $model_name --outfile ./$model_name+'.gguf'
!llama-quantize $model_name.gguf $model_name+$quantization_type.gguf $quantization_type N=?-1?

In [1]:
import benchmark_llm
import time
# for model_name in ['smollm2-q4km','smollm2-iq4xs','smollm2-q80','smollm2-q16pruned']:
for model_name in ['sparsegpt']:
    model_path=f'/mnt/c/Users/PC/Downloads/smolm2-pruned-sparsegpt.gguf'
    benchllm=benchmark_llm.BenchLLM('../../llama.cpp/bin/llama-server','../../llama.cpp/bin/llama-perplexity',model_path)
    time.sleep(30) # wait for previous model free and server to close
    benchllm.start_server()
    time.sleep(240) # wait for model to load
    benchllm.bench() # stop server itself
    benchllm.save_to_file(f'./{model_name}json')

/mnt/d/Inno/Thesis/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
build: 6820 (9b9201f6) with cc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0 for x86_64-linux-gnu
system info: n_threads = 4, n_threads_batch = 4, total_threads = 8

system_info: n_threads = 4 (n_threads_batch = 4) / 8 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 |

main: binding port with default address family
main: HTTP server is listening, hostname: 127.0.0.1, port: 8080, http threads: 7
main: loading model
srv    load_model: loading model '/mnt/c/Users/PC/Downloads/smolm2-pruned-sparsegpt.gguf'
llama_model_loader: loaded meta data with 29 key-value pairs and 218 tensors from /mnt/c/Users/PC/Downloads/smolm2-pruned-sparsegpt.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = Sparsegpt
llama_model_loader: - kv   3:                         general.size_label str              = 1.7B
llama_model_loader: - kv   4:                          llama.block_count u32              = 24
llama_model_loader: - kv   5:                       llama.context_length u32              = 8192
llama_model_loader: - kv   6:                     llama.embedding_length u32              = 2048
llama_model_loader: - kv   7:                  llama.feed_forward_length u32              = 8192
llama_model_loader: - kv   8:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   9:              llama.attention.head_count_kv u32              = 32
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 130000.000000
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  12:                 llama.attention.key_length u32              = 64
llama_model_loader: - kv  13:               llama.attention.value_length u32              = 64
llama_model_loader: - kv  14:                          general.file_type u32              = 1
llama_model_loader: - kv  15:                           llama.vocab_size u32              = 49152
llama_model_loader: - kv  16:                 llama.rope.dimension_count u32              = 64
llama_model_loader: - kv  17:               general.quantization_version u32              = 2
llama_model_loader: - kv  18:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  19:                         tokenizer.ggml.pre str              = smollm
llama_model_loader: - kv  20:                      tokenizer.ggml.tokens arr[str,49152]   = ["<|endoftext|>", "<|im_start|>", "<|...
llama_model_loader: - kv  21:                  tokenizer.ggml.token_type arr[i32,49152]   = [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, ...
llama_model_loader: - kv  22:                      tokenizer.ggml.merges arr[str,48900]   = ["Ġ t", "Ġ a", "i n", "h e", "Ġ Ġ...
llama_model_loader: - kv  23:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  24:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  25:            tokenizer.ggml.padding_token_id u32              = 2
llama_model_loader: - kv  26:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  27:                    tokenizer.chat_template str              = {% for message in messages %}{% if lo...
llama_model_loader: - kv  28:            tokenizer.ggml.add_space_prefix bool             = false
llama_model_loader: - type  f32:   49 tensors
llama_model_loader: - type  f16:  169 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = F16
print_info: file size   = 3.19 GiB (16.00 BPW)
load: printing all EOG tokens:
load:   - 0 ('<|endoftext|>')
load:   - 2 ('<|im_end|>')
load:   - 4 ('<reponame>')
load: special tokens cache size = 17
load: token to piece cache size = 0.3170 MB
print_info: arch             = llama
print_info: vocab_only       = 0
print_info: n_ctx_train      = 8192
print_info: n_embd           = 2048
print_info: n_layer          = 24
print_info: n_head           = 32
print_info: n_head_kv        = 32
print_info: n_rot            = 64
print_info: n_swa            = 0
print_info: is_swa_any       = 0
print_info: n_embd_head_k    = 64
print_info: n_embd_head_v    = 64
print_info: n_gqa            = 1
print_info: n_embd_k_gqa     = 2048
print_info: n_embd_v_gqa     = 2048
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-05
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 8192
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = 0
print_info: rope type        = 0
print_info: rope scaling     = linear
print_info: freq_base_train  = 130000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 8192
print_info: rope_finetuned   = unknown
print_info: model type       = ?B
print_info: model params     = 1.71 B
print_info: general.name     = Sparsegpt
print_info: vocab type       = BPE
print_info: n_vocab          = 49152
print_info: n_merges         = 48900
print_info: BOS token        = 1 '<|im_start|>'
print_info: EOS token        = 2 '<|im_end|>'
print_info: EOT token        = 0 '<|endoftext|>'
print_info: PAD token        = 2 '<|im_end|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM REP token    = 4 '<reponame>'
print_info: EOG token        = 0 '<|endoftext|>'
print_info: EOG token        = 2 '<|im_end|>'
print_info: EOG token        = 4 '<reponame>'
print_info: max token length = 162
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors:   CPU_Mapped model buffer size =  3264.38 MiB
................................................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 4096
llama_context: n_ctx_per_seq = 4096
llama_context: n_batch       = 2048
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = auto
llama_context: kv_unified    = false
llama_context: freq_base     = 130000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (4096) < n_ctx_train (8192) -- the full capacity of the model will not be utilized
llama_context:        CPU  output buffer size =     0.19 MiB
llama_kv_cache:        CPU KV buffer size =   768.00 MiB
llama_kv_cache: size =  768.00 MiB (  4096 cells,  24 layers,  1/1 seqs), K (f16):  384.00 MiB, V (f16):  384.00 MiB
llama_context: Flash Attention was auto, set to enabled
llama_context:        CPU compute buffer size =   104.00 MiB
llama_context: graph nodes  = 751
llama_context: graph splits = 1
common_init_from_params: added <|endoftext|> logit bias = -inf
common_init_from_params: added <|im_end|> logit bias = -inf
common_init_from_params: added <reponame> logit bias = -inf
common_init_from_params: setting dry_penalty_last_n to ctx_size = 4096
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
srv          init: initializing slots, n_slots = 1
slot         init: id  0 | task -1 | new slot n_ctx_slot = 4096
srv          init: prompt cache is enabled, size limit: 8192 MiB
srv          init: use `--cache-ram 0` to disable the prompt cache
srv          init: for more info see https://github.com/ggml-org/llama.cpp/pull/16391
srv          init: thinking = 0
main: model loaded
main: chat template, chat_template: {% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|im_start|>system
You are a helpful AI assistant named SmolLM, trained by Hugging Face<|im_end|>
' }}{% endif %}{{'<|im_start|>' + message['role'] + '
' + message['content'] + '<|im_end|>' + '
'}}{% endfor %}{% if add_generation_prompt %}{{ '<|im_start|>assistant
' }}{% endif %}, example_format: '<|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
Hi there<|im_end|>
<|im_start|>user
How are you?<|im_end|>
<|im_start|>assistant
'
main: server is listening on http://127.0.0.1:8080 - starting the main loop
srv  update_slots: all slots are idle
slot get_availabl: id  0 | task -1 | selected slot by LRU, t_last = -1
slot launch_slot_: id  0 | task 0 | processing task
slot update_slots: id  0 | task 0 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 68
slot update_slots: id  0 | task 0 | n_past = 0, memory_seq_rm [0, end)
slot update_slots: id  0 | task 0 | prompt processing progress, n_past = 68, n_tokens = 68, progress = 1.000000
slot update_slots: id  0 | task 0 | prompt done, n_past = 68, n_tokens = 68
slot print_timing: id  0 | task 0 |
prompt eval time =     763.95 ms /    68 tokens (   11.23 ms per token,    89.01 tokens per second)
       eval time =   23726.97 ms /   256 tokens (   92.68 ms per token,    10.79 tokens per second)
      total time =   24490.92 ms /   324 tokens
slot      release: id  0 | task 0 | stop processing: n_past = 323, truncated = 0
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /completion 127.0.0.1 200
slot get_availabl: id  0 | task -1 | selected slot by LRU, t_last = 13008642045
srv  get_availabl: updating prompt cache
srv   prompt_save:  - saving prompt with length 323, total state size = 60.567 MiB
srv          load:  - looking for better prompt, base f_keep = 0.000, sim = 0.000
srv        update:  - cache state: 1 prompts, 60.567 MiB (limits: 8192.000 MiB, 4096 tokens, 43687 est)
srv        update:    - prompt 0x55cf488caaa0:     323 tokens, checkpoints:  0,    60.567 MiB
srv  get_availabl: prompt cache update took 30.02 ms
slot launch_slot_: id  0 | task 257 | processing task
slot update_slots: id  0 | task 257 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 69
slot update_slots: id  0 | task 257 | n_past = 0, memory_seq_rm [0, end)
slot update_slots: id  0 | task 257 | prompt processing progress, n_past = 69, n_tokens = 69, progress = 1.000000
slot update_slots: id  0 | task 257 | prompt done, n_past = 69, n_tokens = 69
slot print_timing: id  0 | task 257 |
prompt eval time =     726.75 ms /    69 tokens (   10.53 ms per token,    94.94 tokens per second)
       eval time =   23705.00 ms /   256 tokens (   92.60 ms per token,    10.80 tokens per second)
      total time =   24431.75 ms /   325 tokens
slot      release: id  0 | task 257 | stop processing: n_past = 324, truncated = 0
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /completion 127.0.0.1 200
slot get_availabl: id  0 | task -1 | selected slot by LRU, t_last = 13033107055
srv  get_availabl: updating prompt cache
srv   prompt_save:  - saving prompt with length 324, total state size = 60.754 MiB
srv          load:  - looking for better prompt, base f_keep = 0.000, sim = 0.000
srv        update:  - cache state: 2 prompts, 121.321 MiB (limits: 8192.000 MiB, 4096 tokens, 43687 est)
srv        update:    - prompt 0x55cf488caaa0:     323 tokens, checkpoints:  0,    60.567 MiB
srv        update:    - prompt 0x55cf488cd460:     324 tokens, checkpoints:  0,    60.754 MiB
srv  get_availabl: prompt cache update took 28.73 ms
slot launch_slot_: id  0 | task 514 | processing task
slot update_slots: id  0 | task 514 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 89
slot update_slots: id  0 | task 514 | n_past = 0, memory_seq_rm [0, end)
slot update_slots: id  0 | task 514 | prompt processing progress, n_past = 89, n_tokens = 89, progress = 1.000000
slot update_slots: id  0 | task 514 | prompt done, n_past = 89, n_tokens = 89
slot print_timing: id  0 | task 514 |
prompt eval time =    1011.98 ms /    89 tokens (   11.37 ms per token,    87.95 tokens per second)
       eval time =   23281.26 ms /   256 tokens (   90.94 ms per token,    11.00 tokens per second)
      total time =   24293.23 ms /   345 tokens
slot      release: id  0 | task 514 | stop processing: n_past = 344, truncated = 0
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /completion 127.0.0.1 200
slot get_availabl: id  0 | task -1 | selected slot by LRU, t_last = 13057434479
srv  get_availabl: updating prompt cache
srv   prompt_save:  - saving prompt with length 344, total state size = 64.505 MiB
srv          load:  - looking for better prompt, base f_keep = 0.000, sim = 0.000
srv        update:  - cache state: 3 prompts, 185.826 MiB (limits: 8192.000 MiB, 4096 tokens, 43687 est)
srv        update:    - prompt 0x55cf488caaa0:     323 tokens, checkpoints:  0,    60.567 MiB
srv        update:    - prompt 0x55cf488cd460:     324 tokens, checkpoints:  0,    60.754 MiB
srv        update:    - prompt 0x55cf488cc560:     344 tokens, checkpoints:  0,    64.505 MiB
srv  get_availabl: prompt cache update took 31.40 ms
slot launch_slot_: id  0 | task 771 | processing task
slot update_slots: id  0 | task 771 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 91
slot update_slots: id  0 | task 771 | n_past = 0, memory_seq_rm [0, end)
slot update_slots: id  0 | task 771 | prompt processing progress, n_past = 91, n_tokens = 91, progress = 1.000000
slot update_slots: id  0 | task 771 | prompt done, n_past = 91, n_tokens = 91
slot print_timing: id  0 | task 771 |
prompt eval time =     944.83 ms /    91 tokens (   10.38 ms per token,    96.31 tokens per second)
       eval time =   23316.12 ms /   256 tokens (   91.08 ms per token,    10.98 tokens per second)
      total time =   24260.95 ms /   347 tokens
slot      release: id  0 | task 771 | stop processing: n_past = 346, truncated = 0
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /completion 127.0.0.1 200
slot get_availabl: id  0 | task -1 | selected slot by LRU, t_last = 13081729782
srv  get_availabl: updating prompt cache
srv   prompt_save:  - saving prompt with length 346, total state size = 64.880 MiB
srv          load:  - looking for better prompt, base f_keep = 0.000, sim = 0.000
srv        update:  - cache state: 4 prompts, 250.705 MiB (limits: 8192.000 MiB, 4096 tokens, 43687 est)
srv        update:    - prompt 0x55cf488caaa0:     323 tokens, checkpoints:  0,    60.567 MiB
srv        update:    - prompt 0x55cf488cd460:     324 tokens, checkpoints:  0,    60.754 MiB
srv        update:    - prompt 0x55cf488cc560:     344 tokens, checkpoints:  0,    64.505 MiB
srv        update:    - prompt 0x55cf488ce800:     346 tokens, checkpoints:  0,    64.880 MiB
srv  get_availabl: prompt cache update took 32.44 ms
slot launch_slot_: id  0 | task 1028 | processing task
slot update_slots: id  0 | task 1028 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 60
slot update_slots: id  0 | task 1028 | n_past = 0, memory_seq_rm [0, end)
slot update_slots: id  0 | task 1028 | prompt processing progress, n_past = 60, n_tokens = 60, progress = 1.000000
slot update_slots: id  0 | task 1028 | prompt done, n_past = 60, n_tokens = 60
slot print_timing: id  0 | task 1028 |
prompt eval time =     786.40 ms /    60 tokens (   13.11 ms per token,    76.30 tokens per second)
       eval time =   23181.67 ms /   256 tokens (   90.55 ms per token,    11.04 tokens per second)
      total time =   23968.07 ms /   316 tokens
slot      release: id  0 | task 1028 | stop processing: n_past = 315, truncated = 0
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /completion 127.0.0.1 200
slot get_availabl: id  0 | task -1 | selected slot by LRU, t_last = 13105733488
srv  get_availabl: updating prompt cache
srv   prompt_save:  - saving prompt with length 315, total state size = 59.067 MiB
srv          load:  - looking for better prompt, base f_keep = 0.000, sim = 0.000
srv        update:  - cache state: 5 prompts, 309.772 MiB (limits: 8192.000 MiB, 4096 tokens, 43687 est)
srv        update:    - prompt 0x55cf488caaa0:     323 tokens, checkpoints:  0,    60.567 MiB
srv        update:    - prompt 0x55cf488cd460:     324 tokens, checkpoints:  0,    60.754 MiB
srv        update:    - prompt 0x55cf488cc560:     344 tokens, checkpoints:  0,    64.505 MiB
srv        update:    - prompt 0x55cf488ce800:     346 tokens, checkpoints:  0,    64.880 MiB
srv        update:    - prompt 0x55cf488ce3c0:     315 tokens, checkpoints:  0,    59.067 MiB
srv  get_availabl: prompt cache update took 28.30 ms
slot launch_slot_: id  0 | task 1285 | processing task
slot update_slots: id  0 | task 1285 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 72
slot update_slots: id  0 | task 1285 | n_past = 0, memory_seq_rm [0, end)
slot update_slots: id  0 | task 1285 | prompt processing progress, n_past = 72, n_tokens = 72, progress = 1.000000
slot update_slots: id  0 | task 1285 | prompt done, n_past = 72, n_tokens = 72
slot print_timing: id  0 | task 1285 |
prompt eval time =     901.47 ms /    72 tokens (   12.52 ms per token,    79.87 tokens per second)
       eval time =   23130.85 ms /   256 tokens (   90.35 ms per token,    11.07 tokens per second)
      total time =   24032.32 ms /   328 tokens
slot      release: id  0 | task 1285 | stop processing: n_past = 327, truncated = 0
srv  update_slots: all slots are idle
srv  log_server_r: request: POST /completion 127.0.0.1 200
slot get_availabl: id  0 | task -1 | selected slot by LRU, t_last = 13129797468
srv  get_availabl: updating prompt cache
srv   prompt_save:  - saving prompt with length 327, total state size = 61.317 MiB
srv          load:  - looking for better prompt, base f_keep = 0.003, sim = 0.019
srv        update:  - cache state: 6 prompts, 371.089 MiB (limits: 8192.000 MiB, 4096 tokens, 43687 est)
srv        update:    - prompt 0x55cf488caaa0:     323 tokens, checkpoints:  0,    60.567 MiB
srv        update:    - prompt 0x55cf488cd460:     324 tokens, checkpoints:  0,    60.754 MiB
srv        update:    - prompt 0x55cf488cc560:     344 tokens, checkpoints:  0,    64.505 MiB
srv        update:    - prompt 0x55cf488ce800:     346 tokens, checkpoints:  0,    64.880 MiB
srv        update:    - prompt 0x55cf488ce3c0:     315 tokens, checkpoints:  0,    59.067 MiB
srv        update:    - prompt 0x55cf488cc420:     327 tokens, checkpoints:  0,    61.317 MiB
srv  get_availabl: prompt cache update took 29.00 ms
slot launch_slot_: id  0 | task 1542 | processing task
slot update_slots: id  0 | task 1542 | new prompt, n_ctx_slot = 4096, n_keep = 0, n_prompt_tokens = 54
slot update_slots: id  0 | task 1542 | old: ... Which |  tennis player won more Grand S
slot update_slots: id  0 | task 1542 | new: ... Which |  genus of moth in the world
slot update_slots: id  0 | task 1542 |    14413   21059    7081    3763     540    8503     334
slot update_slots: id  0 | task 1542 |    14413   12718     282   25047     281     260     905
slot update_slots: id  0 | task 1542 | n_past = 1, memory_seq_rm [1, end)
slot update_slots: id  0 | task 1542 | prompt processing progress, n_past = 54, n_tokens = 53, progress = 1.000000
slot update_slots: id  0 | task 1542 | prompt done, n_past = 54, n_tokens = 53
slot print_timing: id  0 | task 1542 |
prompt eval time =     623.05 ms /    53 tokens (   11.76 ms per token,    85.07 tokens per second)
       eval time =   22989.35 ms /   256 tokens (   89.80 ms per token,    11.14 tokens per second)

In [2]:
import benchmark_llm
benchllm=benchmark_llm.BenchLLM('../../llama.cpp/bin/llama-server','../../llama.cpp/bin/llama-perplexity','##')
result_df=benchllm.compare_results('.')
result_df

,method,token/sec,accuracy,ppl,flips
0,smollm2-iq4xsjson.json,31.685873202164807+-4.679285929058822,0.115,11.218033+-0.6112230871147706,0.155
1,smollm2-q16pruned.json,10.607968182282585+-0.8920774742859577,0.20212765957446807,16.001023+-0.8810941569081527,nan
2,smollm2-q4km.json,29.627005844926085+-3.470098915617861,0.145,10.983886+-0.6253000362069413,0.145
3,smollm2-q80json.json,18.873430371655708+-2.037660093955812,0.115,10.43017+-0.5873723379740362,0.16
4,sparsegptjson.json,11.017353771035145+-0.2882285739400089,0.145,18.0922205+-1.3367107806046428,0.145

In [3]:
benchllm.calc_corr(result_df)

,token/sec,accuracy,ppl,flips
token/sec,1.00000000000000000000,-0.59989611578508217349,-0.80720439535431731670,0.13777004098380879471
accuracy,-0.59989611578508217349,1.00000000000000000000,0.61348903807775301278,-0.96225044864937681055
ppl,-0.80720439535431731670,0.61348903807775301278,1.00000000000000000000,-0.59374283091397883627
flips,0.13777004098380879471,-0.96225044864937681055,-0.59374283091397883627,1.00000000000000000000

In [ ]:
# non pruned to bf16 gguf
# sparsegpt
# quantization on sparsegpt and wanda models